FROM node:latest

EXPOSE 3000
COPY ./ /home/node/app
WORKDIR /home/node/app
#RUN npm install react-slider
#RUN npm install --save-dev @types/react-slider
RUN npm install react-select --force
RUN npm install
